//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wist.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wist.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert value &apos;{0}&apos; specified in configuration parameter &apos;{1}&apos; to type &apos;{2}&apos; of property &apos;{3}&apos; of class &apos;{4}&apos;..
        /// </summary>
        internal static string ERR_APPLICATION_CONFIGURATION_CONVERSION_FAILED {
            get {
                return ResourceManager.GetString("ERR_APPLICATION_CONFIGURATION_CONVERSION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular class reference detected between classes {0} to {1}..
        /// </summary>
        internal static string ERR_CIRCULAR_CLASS_REFERENCE {
            get {
                return ResourceManager.GetString("ERR_CIRCULAR_CLASS_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve factory Type {0}..
        /// </summary>
        internal static string ERR_FACTORY_TYPE_RESOLUTION_FAILURE {
            get {
                return ResourceManager.GetString("ERR_FACTORY_TYPE_RESOLUTION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate {0} configuration file at: {1}..
        /// </summary>
        internal static string ERR_FAILED_TO_FIND_LOG_CONFIG_FILE {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_FIND_LOG_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize counter &apos;{0}&apos; from category &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_FAILED_TO_INITIALIZE_COUNTER {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_INITIALIZE_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to marshal argument &apos;{0}&apos; to byte array.
        /// </summary>
        internal static string ERR_FAILED_TO_MARCHAL_TO_BYTE_ARRAY {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_MARCHAL_TO_BYTE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash algorithm &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string ERR_HASH_ALGORITHM_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_HASH_ALGORITHM_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Provider {0} not supported..
        /// </summary>
        internal static string ERR_IDENTITY_PROVIDER_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_IDENTITY_PROVIDER_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section of Identity Configuration is missing or corrupted..
        /// </summary>
        internal static string ERR_IDENTITY_PROVIDERS_CONFIGURATION_CORRUPTED {
            get {
                return ResourceManager.GetString("ERR_IDENTITY_PROVIDERS_CONFIGURATION_CORRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of class {0} is not initialized yet. Please invoke its initialization method prior to usage..
        /// </summary>
        internal static string ERR_INSTANCE_IS_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("ERR_INSTANCE_IS_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect {0} requires inheritance/implementation of type {1} that is not implemented by type {2}..
        /// </summary>
        internal static string ERR_MANDATORY_INTERFACE_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_MANDATORY_INTERFACE_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counters service with name &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ERR_PERFORMANCE_COUNTERS_SERVICE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_PERFORMANCE_COUNTERS_SERVICE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate with name &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ERR_PREDICATE_IS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_PREDICATE_IS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifying name of predicate is mandatory.
        /// </summary>
        internal static string ERR_PREDICATE_NAME_IS_MANDATORY {
            get {
                return ResourceManager.GetString("ERR_PREDICATE_NAME_IS_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of work algorithm {0} not supported..
        /// </summary>
        internal static string ERR_PROOF_OF_WORK_ALGORITHM_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_PROOF_OF_WORK_ALGORITHM_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required configuration parameter &apos;{0}&apos; not specified at application configuration file..
        /// </summary>
        internal static string ERR_REQUIRED_CONIGURATION_PARAMETER_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("ERR_REQUIRED_CONIGURATION_PARAMETER_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State service {0} not supported..
        /// </summary>
        internal static string ERR_STATE_SERVICE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_STATE_SERVICE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length must be even..
        /// </summary>
        internal static string ERR_STRING_LEN_EVEN {
            get {
                return ResourceManager.GetString("ERR_STRING_LEN_EVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator from {0} to {1} not found..
        /// </summary>
        internal static string ERR_TRANSLATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_TRANSLATOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration parameter &apos;{0}&apos; has value &apos;{1}&apos; with incorrect format. Expected &apos;{2}&apos;..
        /// </summary>
        internal static string ERR_WRONG_CONFIGURATION_VALUE_FORMAT {
            get {
                return ResourceManager.GetString("ERR_WRONG_CONFIGURATION_VALUE_FORMAT", resourceCulture);
            }
        }
    }
}
