//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wist.BlockLattice.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wist.BlockLattice.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Handler for PacketType {0} is not supported..
        /// </summary>
        internal static string ERR_BLOCK_HANDLER_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_BLOCK_HANDLER_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; is not supported for block type &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_BLOCK_VERSION_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_BLOCK_VERSION_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks Processor with name {0} is not registered..
        /// </summary>
        internal static string ERR_BLOCKS_PROCESSOR_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("ERR_BLOCKS_PROCESSOR_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find block for identity key {0}..
        /// </summary>
        internal static string ERR_FAILED_TO_FIND_BLOCK_BY_IDENTITY_KEY {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_FIND_BLOCK_BY_IDENTITY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity with key value {0} already exist..
        /// </summary>
        internal static string ERR_IDENTITY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERR_IDENTITY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity with key value {0} not found..
        /// </summary>
        internal static string ERR_IDENTITY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_IDENTITY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block type {0} is not supported for parsing on Chain Type {1}..
        /// </summary>
        internal static string ERR_NOT_SUPPORTED_BLOCK_TYPE {
            get {
                return ResourceManager.GetString("ERR_NOT_SUPPORTED_BLOCK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet type handler {0} is not supported..
        /// </summary>
        internal static string ERR_NOT_SUPPORTED_PACKET_TYPE_HANDLER {
            get {
                return ResourceManager.GetString("ERR_NOT_SUPPORTED_PACKET_TYPE_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of previous block hash not provided.
        /// </summary>
        internal static string ERR_PREV_HASH_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("ERR_PREV_HASH_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Type {0} of Chain Type {1} is not supported by Signature Supporting Serializers..
        /// </summary>
        internal static string ERR_SIGNATURE_SUPPORTING_SERIALIZERS_BLOCK_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_SIGNATURE_SUPPORTING_SERIALIZERS_BLOCK_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Type {0} is not supported by Signature Supporting Serializers..
        /// </summary>
        internal static string ERR_SIGNATURE_SUPPORTING_SERIALIZERS_CHAIN_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_SIGNATURE_SUPPORTING_SERIALIZERS_CHAIN_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
    }
}
